/*
 * generated by Xtext 2.31.0
 */
package webtest.dsl.tests

import org.junit.jupiter.api.Test

class WebTestDslParsingTest extends ParseTestBase {
	@Test
	def void loadModel() {
		parse('''
			webtest example.Hello
		''')
	}
}
