/*
 * generated by Xtext 2.35.0
 */
package webtest.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WebTestDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("webtest/dsl/parser/antlr/internal/InternalWebTestDsl.tokens");
	}
}
