/*
 * generated by Xtext 2.35.0
 */
package webtest.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.eclipse.xtext.ui.wizard.template.DefaultTemplateProjectCreator;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class WebTestDslUiModule extends AbstractWebTestDslUiModule {

	public WebTestDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return DefaultTemplateProjectCreator.class;
	}
}
