/*
 * generated by Xtext 2.35.0
 */
package webtest.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import webtest.dsl.WebTestDslRuntimeModule;
import webtest.dsl.WebTestDslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class WebTestDslIdeSetup extends WebTestDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new WebTestDslRuntimeModule(), new WebTestDslIdeModule()));
	}
	
}
