/*
 * generated by Xtext 2.35.0
 */
package webtest.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class WebTestDslIdeModule extends AbstractWebTestDslIdeModule {
}
