/*
 * generated by Xtext 2.31.0
 */
package webtest.dsl.ui.wizard;

import org.eclipse.osgi.util.NLS;

public class Messages extends NLS {
	private static final String BUNDLE_NAME = "webtest.dsl.ui.wizard.messages"; //$NON-NLS-1$
	
	public static String WebTestProject_Label;
	public static String WebTestProject_Description;
	public static String HelloWorldProject_Label;
	public static String HelloWorldProject_Description;
	
	static {
	// initialize resource bundle
	NLS.initializeMessages(BUNDLE_NAME, Messages.class);
	}
	
	private Messages() {
	}
}
