/*
 * generated by Xtext 2.31.0
 */
package webtest.dsl.ui.wizard;

import org.eclipse.xtext.ui.wizard.template.AbstractProjectTemplate;
import org.eclipse.xtext.ui.wizard.template.IProjectTemplateProvider;

/**
 * Create a list with all project templates to be shown in the template new project wizard.
 * 
 * Each template is able to generate one or more projects. Each project can be configured such that any number of files are included.
 */
public class WebTestDslProjectTemplateProvider implements IProjectTemplateProvider {
	@Override
	public AbstractProjectTemplate[] getProjectTemplates() {
		return new AbstractProjectTemplate[] { new WebTestProject() };
	}
}
