/*
 * generated by Xtext 2.35.0
 */
package webtest.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class WebTestDslStandaloneSetup extends WebTestDslStandaloneSetupGenerated {

	public static void doSetup() {
		new WebTestDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
